paths:
  base_data_directory: "/Users/promilaghosh/VS-Code-Projects/ParquetToHuggingFace/data/raw data"
  output_directory: "/Users/promilaghosh/VS-Code-Projects/ParquetToHuggingFace/data/processed_data"

huggingface:
  repo_id: "pr0mila-gh0sh/ParquetToHuggingFace"
  token_env_var: "HUGGINGFACE_TOKEN"
