paths:
  base_data_directory: "./ParquetToHuggingFace/data/raw data"
  output_directory: ./ParquetToHuggingFace/data/processed_data"

huggingface:
  repo_id: "username/repo_id"
  token_env_var: "HUGGINGFACE_TOKEN"
